const defaultItems = [
    "Banana",
    "Avacado",
    "Spinach",
    "Salads",
    "Tomato",
    "Celery",
    "Carrots",
    "Sweet potato",
    "Potato",
    "Onion",
    "Cucumber",
    "Brussel sprouts",
    "Nuts",
    "Chicken breasts",
    "Chicken thighs",
    "Chicken sausages",
    "Sour kraut",
    "Tofu",
    "GF noodles",
    "Gf granola",
    "Tuna",
    "Pickles",
    "Chips",
    "Gallon storage bags",
    "Toothpaste",
    "Toilet paper",
    "Paper towels",
    "Crackers",
    "Gf pizza",
    "Pizza",
    "Burritos",
    "Almond milk",
    "Regular milk",
    "Eggs",
    "Turkey slices",
    "Gf oatmeal",
    "Pepperoni",
    "Kefir",
    "Swiss cheese",
    "Bread",
    "Sourdough bread",
    "Babybell cheese"
  ]

export default defaultItems